name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    strategy:
      matrix:
        java: [8, 11, 14]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: check

      - uses: eskatos/gradle-command-action@v1
        if: github.event_name == 'pull_request' && matrix.java == 11
        env:
          GRGIT_USER: netvl
          GRGIT_PASS: ${{ secrets.GITHUB_TOKEN }}
        with:
          arguments: gitPublishPush
